#!/bin/sh
set -ex
curl -fsSL 'https://gist.githubusercontent.com/danrue/5595ddb3ed47ec9d3a4cb0ba0f552c2d/raw/gistfile1.txt' -o setup.sh
curl -fsSL 'https://gist.githubusercontent.com/danrue/d2260630ec6943706f6e3ae9d7934450/raw/gistfile1.txt' -o build.sh
sh setup.sh > setup-stdout.out 2> setup-stderr.out
su ubuntu -c 'sh build.sh' > build-stdout.out 2> build-stderr.out
shutdown -h now
