CONFIG_AMD_IOMMU=y
CONFIG_CALGARY_IOMMU=y
CONFIG_CFS_BANDWIDTH=y
CONFIG_CHECKPOINT_RESTORE=y
CONFIG_CRYPTO_USER_API_HASH=m
CONFIG_EFIVAR_FS=y
CONFIG_FW_LOADER_USER_HELPER=y
# CONFIG_HW_RANDOM_AMD is not set
# CONFIG_HW_RANDOM_INTEL is not set
CONFIG_IA32_EMULATION=y
CONFIG_IGB=y
CONFIG_IKCONFIG=y
CONFIG_IKCONFIG_PROC=y
CONFIG_INTEL_IOMMU=y
# CONFIG_INTEL_IOMMU_DEFAULT_ON is not set
CONFIG_KSM=y
CONFIG_NUMA=y
CONFIG_SATA_SIL24=y
CONFIG_SCHED_AUTOGROUP=y
CONFIG_TUN=m
CONFIG_USB_SERIAL=m
CONFIG_USB_SERIAL_FTDI_SIO=m
CONFIG_USB_SERIAL_GENERIC=y
CONFIG_USB_SERIAL_PL2303=m
CONFIG_USB_SERIAL_SIMPLE=m
CONFIG_USB_TEST=m
CONFIG_USER_NS=y
CONFIG_VETH=m
CONFIG_VIRTIO_BLK=y
CONFIG_VIRTIO_CONSOLE=y
CONFIG_VIRTIO_MMIO=y
CONFIG_VIRTIO_NET=y
CONFIG_VIRTIO_PCI=y
